# Run the parameter-draws scenarios through BOTH models and save tidy CSVs.
#
#   Rscript validations/04-parameter-draws/run.R                   # about two hours on 4 workers
#   CMP_SMOKE=1 Rscript validations/04-parameter-draws/run.R       # a minute, end to end
#   CMP_FLEET_ONLY=1 Rscript validations/04-parameter-draws/run.R  # fleet's rows only, two minutes
#
# Each draw in results/draws.csv (written by select.R) is run at EIR 3, 20 and
# 120 exactly as the EIR grid of validations/02-scenarios is: the same base
# parameter list, the draw swapped in by set_parameter_draw() before
# set_equilibrium(), the same 30-year burn-in and three-year window, the same
# replicate count and summariser. Only the parameters differ.
#
# The claim measures each draw's change from the default parameters, so fleet
# is also run at the default parameters here. The IBM is not: its
# default-parameter runs are the EIR grid's own eir_3, eir_20 and eir_120 rows
# in validations/02-scenarios, the same scenarios with more rendering bands,
# which change no dynamics (assess.R checks that, and that the rows are current).
#
# Cost: eight draws at three EIRs is 24 scenarios, and 20 IBM replicates of each
# is 480 IBM runs of 33 years, about a minute each.
#
# Do not edit this file while it runs: Rscript reads a script as it goes.

## No absolute paths anywhere in here. FLEET_LIB is prepended to the library
## path, for installations that do not pick up R_LIBS_USER (the Windows-arm64
## setup this was developed on); the libraries already on the path are kept. ROOT
## is found by walking up to the DESCRIPTION, so this runs from any working
## directory and on anyone's checkout, whether via Rscript or source().
if (nzchar(.l <- Sys.getenv("FLEET_LIB"))) .libPaths(c(.l, .libPaths()))
.f <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
ROOT <- if (length(.f)) normalizePath(dirname(.f), "/") else getwd()
while (!file.exists(file.path(ROOT, "DESCRIPTION")) && dirname(ROOT) != ROOT)
  ROOT <- dirname(ROOT)
if (!file.exists(file.path(ROOT, "DESCRIPTION")))
  stop("run this from inside the fleetcheck checkout (no DESCRIPTION found above ", getwd(), ")")
## fc_root() and fc_results() resolve from here, not from the working directory
Sys.setenv(FLEETCHECK_ROOT = ROOT)
suppressMessages(library(malariasimulation))
if (requireNamespace("pkgload", quietly = TRUE) &&
    file.exists(file.path(ROOT, "DESCRIPTION"))) {
  suppressMessages(pkgload::load_all(ROOT, quiet = TRUE))
} else {
  suppressMessages(library(fleetcheck))
}
log_msg <- function(...) cat(sprintf("[%s] %s\n", format(Sys.time(), "%H:%M:%S"), sprintf(...)))
## 0.0.0.9004 follows a draw's iv0, as the IBM does
if (utils::packageVersion("fleet") < "0.0.0.9004")
  stop("fleet ", utils::packageVersion("fleet"), " predates 0.0.0.9004, which reads ",
       "a draw's iv0; install a current fleet.", call. = FALSE)

## The scenario builder, the summariser, run_fleet() and the digest helpers:
## the same copy validations/02-scenarios is measured with.
source(file.path(ROOT, "validations", "_shared", "scenarios.R"))
if (SP != "pf")
  stop("the parameter-draws claim is P. falciparum only; unset CMP_PARASITE.", call. = FALSE)

DDIR <- fc_results("04-parameter-draws")
draws <- read.csv(file.path(DDIR, "draws.csv"), stringsAsFactors = FALSE)
N_WORKERS <- as.integer(Sys.getenv("CMP_WORKERS", "4"))
## CMP_FLEET_ONLY=1 -> re-run only fleet and keep the IBM rows: for a fleet-side
## change, which leaves the IBM's results as they were
FLEET_ONLY <- nzchar(Sys.getenv("CMP_FLEET_ONLY"))
## CMP_SMOKE=1 -> one draw, two replicates (the fewest a band can be drawn
## from), a 4-year horizon (scenarios.R has already cut BURN_Y to 1), to
## results/smoke/. assess.R then needs validations/02-scenarios' own smoke rows.
if (SMOKE) {
  N_REP <- 2L; draws <- draws[1, ]
  DDIR <- file.path(DDIR, "smoke"); dir.create(DDIR, showWarnings = FALSE)
}
PROG <- file.path(DDIR, "progress.log"); if (file.exists(PROG)) invisible(file.remove(PROG))

draw_scen <- list(); ref_scen <- list()
for (E in PROFILE_EIR) ref_scen[[draw_scenario_name(0, E)]] <- draw_scenario(0, E)
for (d in draws$draw) for (E in PROFILE_EIR)
  draw_scen[[draw_scenario_name(d, E)]] <- draw_scenario(d, E)

## ---- fleet: deterministic, once per scenario, here; the default parameters too ----
ode <- run_fleet(c(ref_scen, draw_scen))

## ---- the IBM replicates, on a worker pool -----------------------------------------
ibm <- list()
if (!FLEET_ONLY) {
  jobs <- expand.grid(scenario = names(draw_scen), rep = seq_len(N_REP),
                      stringsAsFactors = FALSE)
  ## the most transmission costs the IBM most: start those runs first
  jobs$eir <- vapply(jobs$scenario, function(nm) draw_scen[[nm]]$eir, numeric(1))
  jobs <- jobs[order(-jobs$eir, jobs$rep), ]; rownames(jobs) <- NULL
  log_msg("%d IBM runs (%d scenarios x %d replicates) on %d workers",
          nrow(jobs), length(draw_scen), N_REP, N_WORKERS)
  cl <- parallel::makeCluster(N_WORKERS)
  .libs <- .libPaths()
  parallel::clusterExport(cl, c("jobs", "draw_scen", "summarise_run", "summarise_run_pv",
                                "tag_parts", "band_lo", "band_hi", "AGE_TAGS", "POP",
                                "PROG", ".libs", "SP"))
  invisible(parallel::clusterEvalQ(cl, {
    .libPaths(.libs)
    suppressMessages(library(malariasimulation))
  }))
  t0 <- Sys.time()
  ibm <- parallel::parLapplyLB(cl, seq_len(nrow(jobs)), function(j) {
    nm <- jobs$scenario[j]; k <- jobs$rep[j]; s <- draw_scen[[nm]]
    ## validations/02-scenarios' seeding. Nothing pairs replicates across
    ## scenarios: a draw changes the dynamics from the first day, and the two
    ## runs' random streams part at once.
    set.seed(1000L + 7L * k)
    el <- system.time(out <- run_simulation(timesteps = s$years * 365, parameters = s$p))[["elapsed"]]
    r <- summarise_run(out, s$years)
    r$timing <- data.frame(years = s$years, elapsed_s = el)
    cat(sprintf("[%s] %-20s rep %2d  %5.1f min\n", format(Sys.time(), "%H:%M:%S"), nm, k,
                el / 60), file = PROG, append = TRUE)
    tag_parts(r, nm, "IBM", k)
  }, chunk.size = 1L)
  parallel::stopCluster(cl)
  log_msg("IBM done in %.1f min", as.numeric(Sys.time() - t0, units = "mins"))
}

## ---- combine and write --------------------------------------------------------------
## draw (0 = the default parameters) and EIR beside the scenario name, so
## nothing downstream parses it
all_scen <- c(ref_scen, draw_scen)
label <- function(d) {
  d$draw <- vapply(d$scenario, function(nm) all_scen[[nm]]$draw, numeric(1))
  d$eir <- vapply(d$scenario, function(nm) all_scen[[nm]]$eir, numeric(1))
  d
}
for (part in c("eq", "timing")) {
  d <- label(do.call(rbind, c(lapply(ode, `[[`, part), lapply(ibm, `[[`, part))))
  f <- file.path(DDIR, paste0("rep_", part, ".csv"))
  if (FLEET_ONLY) {
    if (!file.exists(f)) stop("CMP_FLEET_ONLY needs the committed ", basename(f), call. = FALSE)
    old <- read.csv(f, stringsAsFactors = FALSE)
    ## the IBM rows of the scenarios still defined; a column either side lacks
    ## is filled with NA rather than failing the merge
    old <- old[which(old$model != "fleet" & old$scenario %in% names(all_scen)), ]
    for (nm in setdiff(names(d), names(old))) old[[nm]] <- rep(NA, nrow(old))
    for (nm in setdiff(names(old), names(d))) d[[nm]] <- rep(NA, nrow(d))
    d <- rbind(old[names(d)], d)
  }
  ## rep_eq.csv at full precision: assess.R asserts fleet's rows to 1e-6
  write.csv(round_sig(d, if (part == "eq") NULL else 6), f, row.names = FALSE)
  log_msg("wrote rep_%s.csv (%d rows)", part, nrow(d))
}
## which fleet made its rows
jsonlite::write_json(stamp(age_groups = length(fleet::default_age_lower())),
                     file.path(DDIR, "fleet_reference.json"), auto_unbox = TRUE, pretty = TRUE)

## What the IBM rows were made from, per scenario, so assess.R can tell when a
## definition or malariasimulation itself has moved on from them
if (!FLEET_ONLY && !SMOKE) {
  ref <- list(
    generated = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
    malariasimulation = as.character(utils::packageVersion("malariasimulation")),
    R = paste0(R.version$major, ".", R.version$minor),
    n_rep = N_REP, population = POP, burn_in_years = BURN_Y,
    draws = draws$draw, eir = PROFILE_EIR,
    scenario_digest = scenario_digest(draw_scen),
    scenario_digests = as.list(scenario_digests_each(draw_scen)))
  jsonlite::write_json(ref, file.path(DDIR, "ibm_reference.json"), auto_unbox = TRUE,
                       pretty = TRUE, digits = NA)
  log_msg("wrote ibm_reference.json (%d scenario digests)", length(ref$scenario_digests))
}
log_msg("ALL DONE")
